version: "3.9"  # optional since v1.27.0
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "9000:8080"
    environment:
      SWAGGER_JSON: /swagger.yml
    volumes:
      - ./swagger/swagger.yml:/swagger.yml:ro
