version: "3.9" # optional since v1.27.0
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    restart: always
    ports:
      - "9001:8080"
    environment:
      SWAGGER_JSON: /openapi.yml
    volumes:
      - ./service/openapi.yml:/openapi.yml:ro
