name: Generate GitHub Release

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  release_linux_amd64:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: ~1.17
        cache-key-suffix: ${{ matrix.os }}
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set environment variables
      run: |
        echo "CGO_ENABLED=0 GO111MODULE=on" >> $GITHUB_ENV
        echo "${HOME}/goroot/bin" >> $GITHUB_PATH

    - name: Download dependencies
      run: go mod tidy

    - name: Build application
      run: go build -o ./user-service

    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Project Jano - User Service ${{ steps.getversion.outputs.version }}"
        files: |
          LICENSE
          README.md
          user-service
