on: [push, pull_request]
name: Test application 
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: ~1.17

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod tidy

    - name: Run test
      run: go test ./...
